#!/bin/bash
PATH=bin:$PATH

ref=`basename $0`.ref
alt=`basename $0`.alt
bam=`basename $0`.bam
bed=`basename $0`.bed
vcf=`basename $0`.vcf

trap 'rm -f $ref* $alt $bam* $bed $vcf' EXIT

# 01234567	start
# ATCGGCTA
# 12345678	end

cat >$ref <<REF
>ref
ATCGGCTA
REF
samtools faidx $ref

cat >$alt <<ALT
>alt
GTTAGGTT
ALT

samtools view -b - >$bam <<SAM
@HD	VN:1.5	SO:coordinate
@SQ	SN:ref	LN:8
alt	0	ref	1	30	1X1=2X1=1X1=1X	*	0	0	GTTAGGTT	*
SAM
samtools index $bam

cat >$bed <<BED
ref	0	1	first_base
ref	2	4	third_and_fourth_base
ref	5	6	sixth_base
ref	7	8	eigth_base
BED

cat >$vcf <<VCF
##fileformat=VCFv4.1
##INFO=<ID=NAME,Number=0,Type=String,Description="Test name">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
ref	1	.	A	G	1234	PASS	NAME=first base
ref	2	.	T	.	1234	PASS	NAME=second base
ref	3	.	C	T	1234	PASS	NAME=third base
ref	4	.	G	A	1234	PASS	NAME=fourth base
ref	5	.	G	.	1234	PASS	NAME=fifth base
ref	6	.	C	G	1234	PASS	NAME=sixth base
ref	7	.	T	.	1234	PASS	NAME=seventh base
ref	8	.	A	T	1234	PASS	NAME=eigth base
VCF

PS4='\n+ '

set -x
cat $ref
cat $bed
cat $vcf
vcfannotate --bed $bed --key MATCH $vcf
vcfintersect --bed $bed $vcf
bedtools intersect -a $vcf -b $bed
(freebayes --region ref:4-5 --region ref:6-7 \
    --haplotype-length 0 --min-alternate-count 1 \
	--min-alternate-fraction 0 --pooled-continuous --report-monomorphic \
    --ploidy 1 \
	-f $ref $bam \
    | grep -vE '^##')
(freebayes --region ref:5-6 --region ref:7-8 \
    --haplotype-length 0 --min-alternate-count 1 \
	--min-alternate-fraction 0 --pooled-continuous --report-monomorphic \
    --ploidy 1 \
	-f $ref $bam \
    | grep -vE '^##')
(freebayes --targets $bed \
	--haplotype-length 0 --min-alternate-count 1 \
	--min-alternate-fraction 0 --pooled-continuous --report-monomorphic \
    --ploidy 1 \
	-f $ref $bam \
    | grep -vE '^##')
