#!/usr/bin/env bash

if [ $# -ne 1 ];
then  
echo usage: $0 '[file name]'
echo runs bgzip on the input and tabix indexes the result
echo "== bgzip >[file] && tabix -fp vcf [file]"
exit
fi

file=$1

bgzip >$file && tabix -fp vcf $file
