name: CI
on: [push, pull_request]
jobs:
  arch:
    name: freebayes-CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Guix
      uses: PromyLOPh/guix-install-action@v1
    - name: Configure
      run: guix shell -D -f guix.scm -- meson setup build/ --buildtype debug --wipe
    - name: Compile
      run: guix shell -D -f guix.scm -- ninja -C build/ -v
    - name: Run tests
      run: guix shell -D -f guix.scm -- meson test --timeout-multiplier 4 --print-errorlogs -C build/
    - name: Run regression tests against committed baseline
      run: guix shell -D -f guix.scm -- bash test/regression_test.sh

  build-aarch64:
    name: freebayes-CI aarch64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
